### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by SimplySylvia** [lfonzi62/Project-0-About-Me-Site-#1]
Great site. In my opinion, the line spacing is a bit too much. Makes it hard to read. (Recruiters will just skim it instead of reading it like this) But that is a very small change. Also, I would have liked to see you maybe style the form a bit differently then monument. As for your JS I can see a bit of code from node inside there. I would clean that up and remove it. Also, I can see you used solution code from online for the quotes rotating. I would have liked to see you work through the logic of that manually. Going into the next project I would like to see more notations around the functions with descriptions on what they are doing. Overall good job excited to see what you do in your next project.

**Comment by Shadowcoder12** [comment]
Thank you for the feedback Dalton!
